services:

  mysqldb:
    image: mysql:8.0
    restart: no
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
    command: --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: entrebicis:v1
    restart: no
    depends_on:
      mysqldb:
        condition: service_healthy
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{"spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/entrebicis?createDatabaseIfNotExist=true"}'

volumes:
  db: